// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd3OwXDKauUYMDmIF163-OIr6qpMxbheQ',
    appId: '1:711900003254:web:1a36463de9785b65829f17',
    messagingSenderId: '711900003254',
    projectId: 'flutterfire-8bfdb',
    authDomain: 'flutterfire-8bfdb.firebaseapp.com',
    storageBucket: 'flutterfire-8bfdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3uqT4edCGzieVVZ5lWe7wgq0CkZrY8m4',
    appId: '1:711900003254:android:302a23b361d6d0fe829f17',
    messagingSenderId: '711900003254',
    projectId: 'flutterfire-8bfdb',
    storageBucket: 'flutterfire-8bfdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZc-gj28xNhMUrQlqmXEVIPHXmUSML_ys',
    appId: '1:711900003254:ios:c7a734dbe4b7b973829f17',
    messagingSenderId: '711900003254',
    projectId: 'flutterfire-8bfdb',
    storageBucket: 'flutterfire-8bfdb.appspot.com',
    iosClientId: '711900003254-lo261fsmcr0r1k33t6kovk4vaci3ufk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZc-gj28xNhMUrQlqmXEVIPHXmUSML_ys',
    appId: '1:711900003254:ios:c7a734dbe4b7b973829f17',
    messagingSenderId: '711900003254',
    projectId: 'flutterfire-8bfdb',
    storageBucket: 'flutterfire-8bfdb.appspot.com',
    iosClientId: '711900003254-lo261fsmcr0r1k33t6kovk4vaci3ufk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.last',
  );
}
